# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip    
  displayName: 'Install pip'

- script: |
    pip install --user pipenv    
  displayName: 'Install pipenv'
  
- script: |
    pipenv install
  displayName: 'Install pipenv install'
  
- script: |
    pip install -r requirements.txt
  displayName: 'Install requirements'
    
- script: |
    pip install pyodbc
  displayName: 'Install pyodbc'   
    

- script: |    
    pip install pytest pytest-azurepipelines
  displayName: 'Install pytest azure'
  
- script: |    
    pytest -s --alluredir=./allure-results
  displayName: 'pytest'
  
  

- task: CmdLine@2
  condition: always()
  inputs:
    script: |
      echo Write your commands here
      chmod 755 /home/vsts/work/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb/1.0.0/node_modules/allure-commandline/dist/bin/allure
      echo Hello world


- task: AllureGenerate@1
  condition: always()
  inputs:
    resultsDir: 'allure-results'
    targetDir: 'allure-report/$(Build.BuildNumber)'

